blank_issues_enabled: false
contact_links:
  - name: This repository is not maintained
    url: https://github.com/Clank700/going-mobile-android/fork
    about: Please fork the project if you want to fix, extend, or maintain it.
